probeType       8                              # atom type of ProbeParticle (to choose L-J potential ),e.g. 8 for CO, 54 for Xe
charge         -0.05                           # effective charge of probe particle [e]
stiffness       0.25 0.25 20.00                # [N/m] harmonic spring potential (x,y,R) components, x,y is bending stiffnes (0.24-0.25 is typical for CO) , R particle-tip bond-length stiffnes
r0Probe         0.0 0.0 4.00                   # [\AA] equilibirum position of probe particle (x,y,R) components, R is bond length, x,y introduce tip asymmetry
PBC             True                           # Periodic boundary conditions ? [ True/False ]
gridA           __xgrid__   0.0    0.0             # a-vector of unit cell; recommended format (x,y,0)
gridB            0.0   __ygrid__    0.0             # b-vector of unit cell; recommended format (x,y,0)
gridC            0.0    0.0   20.0             # c-vector of unit cell; recommended format (0,0,z)
scanMin         __xmin__   __ymin__  9.5    # start of scanning (x,y,z), add 4 to the actual coordinates
scanMax         __xmax__   __ymax__    17.9    # end of scanning (x,y,z), add 4 to the actual coordinates
# for ppKPFM on a 20 angstrom height cube file, params.ini file should go from 4-20 (corresponding to 0-16 angstroms height of the cell)
Amplitude        1.0                           # [\AA] oscilation amplitude for conversion Fz->df
scanStep         0.10   0.10    0.02 #0.05
colorscale_kpfm  seismic
